# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Nginx-01 
  config.vm.define "nginx-01" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Nginx-01"
    end
    cfg.vm.host_name = "nginx-01"
    cfg.vm.network "private_network", ip: "192.168.56.11"
    cfg.vm.network "forwarded_port", guest: 22, host: "60011", auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: "8080", auto_correct: true, id: "http"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
    cfg.vm.provision "shell", path: "shell/bash_ssh_conf_4_CentOS.sh"
  end

  # Nginx-02
  config.vm.define "nginx-02" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Nginx-02"
    end
    cfg.vm.host_name = "nginx-02"
    cfg.vm.network "private_network", ip: "192.168.56.12"
    cfg.vm.network "forwarded_port", guest: 22, host: "60012", auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: "8081", auto_correct: true, id: "http"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
    cfg.vm.provision "shell", path: "shell/bash_ssh_conf_4_CentOS.sh"
  end

  # WebServer
  (1..3).each do |i| 
    config.vm.define "webserver-0#{i}" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "WebServer-0#{i}"
      end
      cfg.vm.host_name = "WebServer-0#{i}"
      cfg.vm.network "private_network", ip: "192.168.56.10#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
      cfg.vm.network "forwarded_port", guest: 80, host: "800#{i}", auto_correct: true, id: "http"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
      cfg.vm.provision "shell", path: "shell/bash_ssh_conf_4_CentOS.sh"
    end
  end

  # Ansible Server #
  
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"
  	cfg.vm.provider "virtualbox" do |vb|
	    vb.name = "Ansible-Server"
	  end
	  cfg.vm.host_name = "ansible-server"
	  cfg.vm.network "private_network", ip: "192.168.56.10"
	  cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
	  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: "yum install epel-release -y"
	  cfg.vm.provision "shell", inline: "yum install ansible -y"
    cfg.vm.provision "file", source: "./yaml/ansible_env_ready.yml", 
       destination: "ansible_env_ready.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
    cfg.vm.provision "file", source: "./yaml/auto_pass.yml", destination: "auto_pass.yml"
	  cfg.vm.provision "shell", inline: "ansible-playbook auto_pass.yml", privileged: false
    cfg.vm.provision "file", source: "./yaml/nginx_install.yml", destination: "nginx_install.yml"
	  cfg.vm.provision "shell", inline: "ansible-playbook nginx_install.yml", privileged: false
  end
end